### ISSUE TITLE
Fatal error : 2.0 Beta 3

### ISSUE THREAD

**Issue by numanzahid** [boospot/boo-recipes#2]
cant activate the plugin. there is a fatal error. 

`Fatal error: Cannot redeclare var_dump_pretty() (previously declared in /home/username/public_html/domain/wp-content/plugins/woobooks_1.0.2/includes/helper-functions.php:19) in /home/user/public_html/domain/wp-content/plugins/boo-recipes/includes/helper-functions.php on line 289`

**Comment by boospot** [comment]
issue has been resolved in release https://github.com/boospot/boo-recipes/releases/tag/2.0-beta-4
